// src/app/accuracy/page.tsx
'use client';

import React, { useState, useEffect, useCallback, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { listAllJobs, getJobStatus, JobSummary, JobStatusResponse, getDownloadLinks } from '@/utils/api';

// ─── Types ────────────────────────────────────────────────────────────────────

interface ScoreItem {
  label: string;
  score: number;
  max: number;
  color: string;
  detail: string;
  tips: string[];
}

interface AccuracyReport {
  jobId: string;
  filename: string;
  overallScore: number;
  scores: ScoreItem[];
  generatedAt: string;
}

// ─── Scoring logic ────────────────────────────────────────────────────────────

function computeAccuracyReport(job: JobStatusResponse, jobId: string): AccuracyReport {
  const scenes = job.scenes || [];
  const total = scenes.length;

  // 1. Story Coverage: % of scenes that have image + audio (both required for video)
  const fullScenes = scenes.filter(s => s.image_path && s.audio_path).length;
  const coverageScore = total > 0 ? Math.round((fullScenes / total) * 100) : 0;

  // 2. Image Fidelity: % of scenes that used a real AI provider (non-placeholder)
  // We check if image_path is set (any path means either real or placeholder)
  const imgScenes = scenes.filter(s => s.image_path).length;
  const imgScore = total > 0 ? Math.round((imgScenes / total) * 100) : 0;

  // 3. Audio Completeness: % scenes with voice narration
  const audioScenes = scenes.filter(s => s.audio_path).length;
  const audioScore = total > 0 ? Math.round((audioScenes / total) * 100) : 0;

  // 4. Subtitle Coverage: % scenes with subtitle file
  const subScenes = scenes.filter(s => s.subtitle_path).length;
  const subScore = total > 0 ? Math.round((subScenes / total) * 100) : 0;

  // 5. Scene Yield: scenes-to-words ratio target. Ideal is 1 scene per ~45 words.
  // We assess if scene count is "reasonable" (not too low or too high)
  let yieldScore = 0;
  if (total >= 3) yieldScore = 60;   // minimum viable
  if (total >= 6) yieldScore = 75;
  if (total >= 10) yieldScore = 88;
  if (total >= 15) yieldScore = 95;
  if (total >= 20) yieldScore = 100;

  // 6. Pipeline Completion: did it finish fully (100% completed)?
  const completionScore = job.status === 'completed' ? 100 : job.progress_percent;

  // Weighted overall score
  const overall = Math.round(
    coverageScore * 0.30 +  // most important
    audioScore   * 0.25 +
    imgScore     * 0.20 +
    subScore     * 0.10 +
    yieldScore   * 0.10 +
    completionScore * 0.05
  );

  const scores: ScoreItem[] = [
    {
      label: 'Scene Coverage',
      score: coverageScore,
      max: 100,
      color: coverageScore >= 85 ? '#10b981' : coverageScore >= 60 ? '#f59e0b' : '#ef4444',
      detail: `${fullScenes}/${total} scenes have both image and audio`,
      tips: coverageScore < 100
        ? [
            'Failed scenes occur when image or voice APIs hit rate limits.',
            'Retry: use the "Re-run Images" or "Re-run Voice" buttons in Studio.',
            'Consider splitting large stories into smaller chunks (≤20 scenes).',
          ]
        : ['Perfect! All scenes generated successfully.'],
    },
    {
      label: 'Voice Completeness',
      score: audioScore,
      max: 100,
      color: audioScore >= 90 ? '#10b981' : audioScore >= 70 ? '#f59e0b' : '#ef4444',
      detail: `${audioScenes}/${total} scenes have narration audio`,
      tips: audioScore < 100
        ? [
            'Missing audio usually means VoiceForge was unreachable.',
            'Ensure your laptop server is running when generation starts.',
            'Re-run voice from Studio → Re-run Voice to fill gaps.',
          ]
        : ['All scenes narrated successfully.'],
    },
    {
      label: 'Image Fidelity',
      score: imgScore,
      max: 100,
      color: imgScore >= 90 ? '#10b981' : imgScore >= 70 ? '#f59e0b' : '#ef4444',
      detail: `${imgScenes}/${total} scenes have generated images`,
      tips: imgScore < 100
        ? [
            'Some scenes fell back to placeholder images when all AI providers failed.',
            'Check your GEMINI_API_KEY and POLLINATIONS_API_KEY in .env.',
            'Retry image generation from Studio → Re-run Images.',
          ]
        : ['All scene images generated by AI — excellent fidelity!'],
    },
    {
      label: 'Subtitle Accuracy',
      score: subScore,
      max: 100,
      color: subScore >= 85 ? '#10b981' : subScore >= 60 ? '#f59e0b' : '#ef4444',
      detail: `${subScenes}/${total} scenes have subtitle transcriptions`,
      tips: subScore < 100
        ? [
            'Subtitles are generated by Whisper speech recognition.',
            'Missing subtitles occur when audio transcription fails.',
            'Re-run subtitles from Studio Workbench to fill gaps.',
          ]
        : ['All scenes have synchronized subtitle tracks.'],
    },
    {
      label: 'Scene Yield',
      score: yieldScore,
      max: 100,
      color: yieldScore >= 88 ? '#10b981' : yieldScore >= 70 ? '#f59e0b' : '#ef4444',
      detail: `${total} scenes extracted from your story`,
      tips: yieldScore < 80
        ? [
            'Fewer scenes means shorter, less detailed video content.',
            'Aim for stories of 500–1500 words for optimal scene density.',
            'Each paragraph of ~45 words typically generates one scene.',
          ]
        : ['Scene count is in the optimal range for video generation.'],
    },
    {
      label: 'Pipeline Completion',
      score: completionScore,
      max: 100,
      color: completionScore === 100 ? '#10b981' : completionScore >= 75 ? '#f59e0b' : '#ef4444',
      detail: job.status === 'completed'
        ? 'All 7 pipeline stages completed'
        : `Stopped at ${job.progress_percent}% — status: ${job.status}`,
      tips: job.status !== 'completed'
        ? [
            `Pipeline failed at: ${job.current_step || 'unknown step'}.`,
            'Review the System Console Logs in Studio for detailed error messages.',
            'Common causes: API quota exceeded, FFmpeg not installed, or disk full.',
          ]
        : ['Full pipeline completed — video, thumbnail, and metadata all generated.'],
    },
  ];

  return {
    jobId,
    filename: job.story_filename || 'Unknown Story',
    overallScore: overall,
    scores,
    generatedAt: new Date().toLocaleString(),
  };
}

// ─── Score Ring component ─────────────────────────────────────────────────────

function ScoreRing({ score, size = 80, color }: { score: number; size?: number; color: string }) {
  const radius = (size - 12) / 2;
  const circ = 2 * Math.PI * radius;
  const offset = circ - (score / 100) * circ;

  return (
    <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
      <circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth={6} />
      <circle
        cx={size / 2}
        cy={size / 2}
        r={radius}
        fill="none"
        stroke={color}
        strokeWidth={6}
        strokeDasharray={circ}
        strokeDashoffset={offset}
        strokeLinecap="round"
        style={{ transition: 'stroke-dashoffset 1.2s cubic-bezier(0.34, 1.56, 0.64, 1)' }}
      />
    </svg>
  );
}

// ─── Main Accuracy Page ───────────────────────────────────────────────────────

function AccuracyPageInner() {
  const searchParams = useSearchParams();
  const initialJobId = searchParams?.get('job_id') || '';

  const [jobs, setJobs] = useState<JobSummary[]>([]);
  const [selectedJobId, setSelectedJobId] = useState(initialJobId);
  const [report, setReport] = useState<AccuracyReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [loadingJobs, setLoadingJobs] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const isAdmin = typeof window !== 'undefined' && localStorage.getItem('storyforge_role') === 'admin';
    listAllJobs(100, isAdmin)
      .then(data => {
        const completed = data.jobs.filter(j => j.status === 'completed');
        setJobs(completed);
        if (!selectedJobId && completed.length > 0) {
          setSelectedJobId(completed[0].job_id);
        }
      })
      .catch(() => {})
      .finally(() => setLoadingJobs(false));
  }, [selectedJobId]);

  const generateReport = useCallback(async (jobId: string) => {
    if (!jobId) return;
    setLoading(true);
    setError(null);
    setReport(null);
    try {
      const status = await getJobStatus(jobId);
      const computed = computeAccuracyReport(status, jobId);
      setReport(computed);
    } catch (err: any) {
      setError(err.message || 'Failed to load job data.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (selectedJobId) {
      generateReport(selectedJobId);
    }
  }, [selectedJobId, generateReport]);

  const overallGrade = (score: number) => {
    if (score >= 90) return { letter: 'A', label: 'Excellent', color: '#10b981' };
    if (score >= 75) return { letter: 'B', label: 'Good', color: '#06b6d4' };
    if (score >= 60) return { letter: 'C', label: 'Average', color: '#f59e0b' };
    if (score >= 40) return { letter: 'D', label: 'Needs Work', color: '#f97316' };
    return { letter: 'F', label: 'Poor', color: '#ef4444' };
  };

  return (
    <div style={{ padding: '40px max(4vw, 24px)', maxWidth: '1100px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: '32px' }}>
        <h1 style={{
          fontSize: '2rem',
          fontWeight: 800,
          background: 'linear-gradient(135deg, #8b5cf6 0%, #06b6d4 100%)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          marginBottom: '8px',
        }}>
          📊 Accuracy Report
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1rem' }}>
          Analyze how accurately and completely your story was converted to video.
          Get scores for each pipeline stage and tips to improve.
        </p>
      </div>

      {/* Job Selector */}
      <div className="glass" style={{ padding: '24px', marginBottom: '28px', display: 'flex', gap: '16px', alignItems: 'center', flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: '240px' }}>
          <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 600, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Select Completed Video
          </label>
          {loadingJobs ? (
            <p style={{ color: 'var(--text-muted)' }}>Loading productions...</p>
          ) : jobs.length === 0 ? (
            <p style={{ color: 'var(--text-muted)' }}>No completed videos found. <Link href="/studio" style={{ color: 'var(--accent-purple)' }}>Create one first.</Link></p>
          ) : (
            <select
              value={selectedJobId}
              onChange={e => setSelectedJobId(e.target.value)}
              style={{
                width: '100%',
                background: 'rgba(255,255,255,0.04)',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '8px',
                color: 'var(--text-primary)',
                padding: '10px 14px',
                fontSize: '0.95rem',
                outline: 'none',
                cursor: 'pointer',
              }}
            >
              {jobs.map(j => (
                <option key={j.job_id} value={j.job_id} style={{ background: '#1a1a2e' }}>
                  {j.story_filename || 'Untitled'} — {j.job_id.substring(0, 8)}... {j.username ? `(${j.username})` : ''}
                </option>
              ))}
            </select>
          )}
        </div>
        <button
          type="button"
          onClick={() => generateReport(selectedJobId)}
          disabled={!selectedJobId || loading}
          style={{
            padding: '11px 24px',
            background: 'linear-gradient(135deg, #8b5cf6, #06b6d4)',
            border: 'none',
            borderRadius: '8px',
            color: '#fff',
            fontWeight: 700,
            fontSize: '0.95rem',
            cursor: 'pointer',
            opacity: loading || !selectedJobId ? 0.6 : 1,
            whiteSpace: 'nowrap',
            alignSelf: 'flex-end',
          }}
        >
          {loading ? '⏳ Analyzing...' : '🔍 Analyze'}
        </button>
      </div>

      {/* Error State */}
      {error && (
        <div className="glass" style={{ padding: '20px', marginBottom: '24px', borderLeft: '3px solid #ef4444', color: '#ef4444' }}>
          ❌ {error}
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div style={{ textAlign: 'center', padding: '60px' }}>
          <svg className="animate-spin-fast" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--accent-purple)" strokeWidth="2.5" style={{ margin: '0 auto 16px' }}>
            <circle cx="12" cy="12" r="10" strokeOpacity="0.25"/>
            <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83"/>
          </svg>
          <p style={{ color: 'var(--text-secondary)' }}>Analyzing pipeline results...</p>
        </div>
      )}

      {/* Report */}
      {report && !loading && (
        <>
          {/* Overall Score Hero */}
          <div className="glass" style={{
            padding: '36px',
            marginBottom: '28px',
            display: 'flex',
            alignItems: 'center',
            gap: '32px',
            flexWrap: 'wrap',
            position: 'relative',
            overflow: 'hidden',
          }}>
            <div style={{
              position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
              background: `radial-gradient(ellipse at top left, ${overallGrade(report.overallScore).color}18 0%, transparent 60%)`,
              pointerEvents: 'none',
            }} />

            {/* Ring */}
            <div style={{ position: 'relative', flexShrink: 0 }}>
              <ScoreRing score={report.overallScore} size={120} color={overallGrade(report.overallScore).color} />
              <div style={{
                position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)',
                textAlign: 'center',
              }}>
                <div style={{ fontSize: '2rem', fontWeight: 900, color: overallGrade(report.overallScore).color, lineHeight: 1 }}>
                  {overallGrade(report.overallScore).letter}
                </div>
                <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)', fontWeight: 600 }}>
                  {report.overallScore}/100
                </div>
              </div>
            </div>

            {/* Summary Text */}
            <div style={{ flex: 1, minWidth: '200px' }}>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', fontWeight: 600, marginBottom: '6px' }}>
                Overall Accuracy Score
              </div>
              <div style={{ fontSize: '2.2rem', fontWeight: 900, color: 'var(--text-primary)', lineHeight: 1.1, marginBottom: '4px' }}>
                {overallGrade(report.overallScore).label}
              </div>
              <div style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', marginBottom: '12px' }}>
                {report.filename}
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                Analyzed at {report.generatedAt}
              </div>
            </div>

            {/* Quick Action */}
            <Link
              href={`/studio/${report.jobId}`}
              style={{
                padding: '12px 24px',
                background: 'linear-gradient(135deg, #8b5cf6, #6d28d9)',
                borderRadius: '10px',
                color: '#fff',
                textDecoration: 'none',
                fontWeight: 700,
                fontSize: '0.9rem',
                flexShrink: 0,
                boxShadow: '0 0 20px rgba(139, 92, 246, 0.3)',
              }}
            >
              🎬 Open in Studio
            </Link>
          </div>

          {/* Score Cards Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '20px', marginBottom: '32px' }}>
            {report.scores.map(item => (
              <div
                key={item.label}
                className="glass"
                style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}
              >
                {/* Label & Score */}
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ fontSize: '0.95rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                    {item.label}
                  </span>
                  <span style={{
                    fontSize: '1.1rem',
                    fontWeight: 900,
                    color: item.color,
                    background: `${item.color}18`,
                    padding: '3px 10px',
                    borderRadius: '20px',
                    border: `1px solid ${item.color}44`,
                  }}>
                    {item.score}%
                  </span>
                </div>

                {/* Progress Bar */}
                <div style={{ height: '8px', background: 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                  <div style={{
                    height: '100%',
                    width: `${item.score}%`,
                    background: item.color,
                    borderRadius: '4px',
                    transition: 'width 1s cubic-bezier(0.34, 1.56, 0.64, 1)',
                  }} />
                </div>

                {/* Detail */}
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', margin: 0 }}>
                  {item.detail}
                </p>

                {/* Tips */}
                <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '12px' }}>
                  <div style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '8px' }}>
                    {item.score >= 90 ? '✅ Notes' : '💡 How to Improve'}
                  </div>
                  <ul style={{ margin: 0, paddingLeft: '16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                    {item.tips.map((tip, i) => (
                      <li key={i} style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                        {tip}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>

          {/* Bottom CTA */}
          {report.overallScore < 80 && (
            <div className="glass" style={{
              padding: '28px',
              borderLeft: '3px solid #f59e0b',
              display: 'flex',
              alignItems: 'center',
              gap: '24px',
              flexWrap: 'wrap',
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, color: '#f59e0b', marginBottom: '6px' }}>⚡ Improve this video</div>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', margin: 0 }}>
                  Open the Studio to re-run individual pipeline stages for failed scenes without reprocessing the entire story.
                </p>
              </div>
              <Link
                href={`/studio/${report.jobId}`}
                style={{
                  padding: '12px 24px',
                  background: 'linear-gradient(135deg, #f59e0b, #d97706)',
                  borderRadius: '10px',
                  color: '#000',
                  textDecoration: 'none',
                  fontWeight: 700,
                  fontSize: '0.9rem',
                  flexShrink: 0,
                }}
              >
                🔧 Fix in Studio
              </Link>
            </div>
          )}
        </>
      )}

      {/* Empty State */}
      {!report && !loading && !error && (
        <div className="glass" style={{ padding: '60px', textAlign: 'center', color: 'var(--text-muted)' }}>
          <div style={{ fontSize: '3rem', marginBottom: '16px' }}>📈</div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-secondary)' }}>
            Select a completed video to analyze
          </h3>
          <p style={{ fontSize: '0.9rem' }}>
            Choose a production from the dropdown above to generate its accuracy report.
          </p>
        </div>
      )}
    </div>
  );
}

export default function AccuracyPage() {
  return (
    <Suspense fallback={
      <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
        Loading...
      </div>
    }>
      <AccuracyPageInner />
    </Suspense>
  );
}
